### ISSUE TITLE
Backface Culling

### ISSUE THREAD

**Issue by CiPH3R-NFS** [AeroWidescreen/NFSHDReflections#10]
Hello Aero, backface culling broke in latest version but works fine in older version.
here are some sample images Steering wheel, Rear Turbo, See through Fenders.

![image-10.png](https://github.com/AeroWidescreen/NFSHDReflections/assets/135097919/437d0dc1-fa10-4700-a579-09258738b841)

![image-9.png](https://github.com/AeroWidescreen/NFSHDReflections/assets/135097919/a2bd3b56-e6bc-4909-b353-5adf3ab6724f)

![image-17.png](https://github.com/AeroWidescreen/NFSHDReflections/assets/135097919/d4f20c5f-53ec-4903-a64b-122cc95368fd)

**Comment by AeroWidescreen** [comment]
Have you tried using `DisableBackFaceCulling = 1` in the `[EXTRA]` section? That's all the older versions were doing; backface culling was being disabled.

**Comment by CiPH3R-NFS** [comment]
Yes I did Disable BackFaceCulling and set it 1
but the issue still continues, can it be the car part itself that needs fixing, when i switch to older version of HD-REFLECTIONS, They appear coorectly.
![Screenshot 2024-01-17 165140](https://github.com/AeroWidescreen/NFSHDReflections/assets/135097919/39081c12-4f5c-4e81-98ee-6b1cc6f7392f)
![Screenshot 2024-01-17 165358](https://github.com/AeroWidescreen/NFSHDReflections/assets/135097919/445e50c0-1b52-4959-a2b7-60eb7b5a5913)
![Screenshot 2024-01-17 165228](https://github.com/AeroWidescreen/NFSHDReflections/assets/135097919/122882cf-0423-46d8-a155-70a97c47aca1)

**Comment by AeroWidescreen** [comment]
My guess is that the car mod itself is to blame, since these issues do not occur with any of the vanilla cars, and I haven't seen any evidence of this occurring with other mod cars. This is all that `DisableBackfaceCulling` does; it's a single line of code that you can easily replicate with Cheat Engine: `008FAE44 00000000` https://github.com/AeroWidescreen/NFSHDReflections/blob/437ae1e3f598e20033046e7b7c0f23d3a2ee9845/SOURCE/NFSMW/dllmain.cpp#L220-L223

The only other feature that cause an issue like this is `RestoreBackfaceCulling` in the `[GENERAL]` section. Don't get the two of these features confused, they do different things. Try disabling that, while keeping `DisableBackfaceCulling` in the `[EXTRA]` section enabled. Keep in mind though that even if this works for you, the problem is still likely still the car mod itself and there's nothing I can do about it on my end.

**Comment by CiPH3R-NFS** [comment]
Thanks for replying, I'll check with my settings HD Reflection & also look into car mod and make those fixes & make everything appears correctly 👍🏻
