### ISSUE TITLE
NFSU2HD Reflections performance issues

### ISSUE THREAD

**Issue by Zergei** [AeroWidescreen/NFSHDReflections#6]
I did a fresh install of Need for Speed Underground 2 v1.2 and only installed the Widescreen Fix first the game run smoothly with all graphical settings maxed out but. then i install the HD Reflections script and thats were the problems started the fps in certain places like  there is 4 fountains or when i face the big city with the fps drops from 60  to 30 or even 25 dont know what the problem is. the only fix is to remove the HD Reflections script and the performance issues dissapear so i dont know whats going on with the script 

left my PC specs just in case 
CPU 
AMD FX-8350	
RAM
16,0GB Dual-Channel DDR3
Motherboard
ASUSTeK Computer INC. M5A78L-M LX PLUS (AM3R2)
Graphics
4095MB NVIDIA GeForce GTX 970 (MSI)

if you need some video or log files tell me and i shall provide them

thanks in advance

**Comment by AeroWidescreen** [comment]
1. Try using `ExtendRenderDistance = 0` and `ImproveReflectionLOD = 0.` 
2. Update your Widescreen Fix. Older versions used a `SingleCoreAffinity` feature that limited the game to one core. This would have a _significant_ impact on your framerate with such an old CPU.

I suspect your CPU is the limiting factor, since even low-end Ryzen processors will outperform it by a significant margin. But, that's only my theory. ExtendRenderDistance and ImproveReflectionLOD affect CPU performance because they increase the amount of draw calls. This affects your GPU as well, but I don't think that's a problem because...

A GTX 970 is about equal to an RX 480 / GTX 1060, which is what I originally designed HD Reflections for, but the performance you get will also depend on your resolution. What are you using? 1080p? 1440p? 4K? HD Reflections automatically scales to your desktop resolution, so if you have a 4K monitor then that could be a problem as well.

**Comment by Zergei** [comment]
> 1. Try using `ExtendRenderDistance = 0` and `ImproveReflectionLOD = 0.`
> 2. Update your Widescreen Fix. Older versions used a `SingleCoreAffinity` feature that limited the game to one core. This would have a _significant_ impact on your framerate with such an old CPU.
> 
> I suspect your CPU is the limiting factor, since even low-end Ryzen processors will outperform it by a significant margin. But, that's only my theory. ExtendRenderDistance and ImproveReflectionLOD affect CPU performance because they increase the amount of draw calls. This affects your GPU as well, but I don't think that's a problem because...
> 
> A GTX 970 is about equal to an RX 480 / GTX 1060, which is what I originally designed HD Reflections for, but the performance you get will also depend on your resolution. What are you using? 1080p? 1440p? 4K? HD Reflections automatically scales to your desktop resolution, so if you have a 4K monitor then that could be a problem as well.

1.- tested the settings you recommend me and works perfectly smooth
2.- about that that setting is on in widescreen fixes by default but that not seems to be the issue
3.- regarding my resolution i use 1366 x 768

**Comment by AeroWidescreen** [comment]
Good to hear, I guess my theory was right then. You can try re-enabling `ImproveReflectionLOD` if you want to give that a try. Leave `SingleCoreAffinity` enabled since that's suppose to help with stability. Just wanted to see if that made a difference at all, which it doesn't, so yeah, leave it on.

Now much else you can do other than upgrading your hardware. Ryzen 3600 + B450 motherboard + 16 GB of DDR4 is relatively cheap these days. Maybe $300 for everything? At least those are the prices where I live. Ideally, you would want to get a 5600X with DDR5, but that's going to be more expensive obviously. 

Anyway, I think this issue can be closed now. Good luck!

**Comment by Zergei** [comment]
> Good to hear, I guess my theory was right then. You can try re-enabling `ImproveReflectionLOD` if you want to give that a try. Leave `SingleCoreAffinity` enabled since that's suppose to help with stability. Just wanted to see if that made a difference at all, which it doesn't, so yeah, leave it on.
> 
> Not much else you can do other than upgrading your hardware. Ryzen 3600 + B450 motherboard + 16 GB of DDR4 is relatively cheap these days. Maybe $300 for everything? At least those are the prices where I live. Ideally, you would want to get a 5600X with DDR5, but that's going to be more expensive obviously.
> 
> Anyway, I think this issue can be closed now. Good luck!

did the test of enable ImproveReflectionLOD  the fps drop was hard so i disable it.  the ryzen setup you gave me is a big NO at least here PC part are 40% or even 50% more expensive than other countries. this pc i have now was a gift from my friend.  i used to have a Phenom 955 X4 3.2 + 8 gb of ram and a GTX 550ti to play games so this gift of PC came from the heavens
