### ISSUE TITLE
Incorrect car reflections, in the front-end(Most Wanted) 

### ISSUE THREAD

**Issue by AlexandrR29** [AeroWidescreen/NFSHDReflections#7]
Problem on the screenshot.
![image](https://github.com/AeroWidescreen/NFSHDReflections/assets/43050308/0bcfe5d4-fa86-4233-b8ac-ad81c33c7779)

Incorrect car reflections, in the garage, car lot and tuning shop.

Problem started, after last HD Reflections update. Also, i`m used Front-End Shadows mod.

**Comment by AeroWidescreen** [comment]
Can't reproduce issue:

![FrontEnd](https://i.imgur.com/XcxnfI8.png)

1. If you remove HD Reflections does the problem go away?
2. If you use HD Reflections with vanilla MW (_no mods_ besides widescreen fix) does the problem go away?
3. What are your PC specs? GPU, CPU, OS, etc.

I'm asking because I know older versions of the Xbox 360 Shader mod changed the reflection resolution and the previous version of HD Reflections used code to overwrite that. Your screenshot shows what happens when that code doesn't exist.

**Comment by AlexandrR29** [comment]
> Can't reproduce issue:
> 
> ![FrontEnd](https://camo.githubusercontent.com/124694456bc3a6e87f6fed8474e633dffeeeaeff9814ddc70d1f897a4f260e15/68747470733a2f2f692e696d6775722e636f6d2f5863786e6649382e706e67)
> 
> 1. If you remove HD Reflections does the problem go away?
> 2. If you use HD Reflections with vanilla MW (_no mods_ besides widescreen fix) does the problem go away?
> 3. What are your PC specs? GPU, CPU, OS, etc.
> 
> I'm asking because I know older versions of the Xbox 360 Shader mod changed the reflection resolution and the previous version of HD Reflections used code to overwrite that. Your screenshot shows what happens when that code doesn't exist.

I`m reproduced this bug. This problem, started if you have MW360 Tweaks.asi, in the game folder, or Scripts folder. Try add this plugin and launch game. 
[MW360Tweaks.zip](https://github.com/AeroWidescreen/NFSHDReflections/files/11909909/MW360Tweaks.zip)

If you deleted this file - reflections works correctly. Before HD Reflections update, with MW360Tweaks, problems not existed.

**Comment by AeroWidescreen** [comment]
> MW360Tweaks.asi

This is an old outdated mod, and the problem you are experiencing is caused by this mod. It is not a problem with HD Reflections.

Please use the latest version of Xbox 360 Stuff Pack and delete MW360Tweaks,asi
https://nfsmods.xyz/mod/1200
