### ISSUE TITLE
Sun flare in vehicle reflections

### ISSUE THREAD

**Issue by TorutheRedFox** [AeroWidescreen/NFSHDReflections#8]
The sun flare shouldn't appear in vehicle reflections in Most Wanted, as the sun is handled by the specular in the shader instead.

**Comment by TorutheRedFox** [comment]
![image](https://github.com/AeroWidescreen/NFSHDReflections/assets/15708278/cb408803-8a03-465a-8ad6-5daa8609b397)

**Comment by AeroWidescreen** [comment]
I went ahead and removed this function entirely because I couldn't think of any instance where this would be useful. The skybox (and mirror) uses a more sophisticated system for the sun. This flare texture is probably a leftover from 6th gen consoles that had no specular to rely on.

Anyway, I added this as a feature called `RemoveLastGenSunFlare`. It's enabled by default. I do not plan to update HD Reflections at this very moment, but you should be able to build it yourself very easily. V**isual Studio 2022 + Desktop Development with C++** is all you need.
https://github.com/AeroWidescreen/NFSHDReflections/commit/9fb971cfcff63a9517a03044872195ae626f471b

**Comment by TorutheRedFox** [comment]
okay thanks

**Comment by TorutheRedFox** [comment]
as for the cg versions, they _do_ have specular, but it's pretty weak on PS2 and GameCube all things considered, so this might be acting as a bit of a boost
